resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/datianshi/testpipeline.git
    branch: master

jobs:
- name: hello-world
  plan:
  - get: source-code
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world!"]

- name: hello-world2
  plan:
  - get: source-code
    passed: hello-world
    trigger: false
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world!"]
